name: swm_icons
description: "The SWM Icon pack for Flutter. Provides 200+ additional icons to use in your apps."
version: 0.2.1
homepage: https://github.com/arifai/swm_icons
repository: https://github.com/arifai/swm_icons
issue_tracker: https://github.com/arifai/swm_icons/issues
topics:
  - assets
  - icons
  - swm
  - swm-icons

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: SWMIconsBroken
      fonts:
        - asset: fonts/SWMIconsBroken.ttf
    - family: SWMIconsCurved
      fonts:
        - asset: fonts/SWMIconsCurved.ttf
    - family: SWMIconsOutline
      fonts:
        - asset: fonts/SWMIconsOutline.ttf